### ISSUE TITLE
Terraform version and language update - .12.x / HCL2

### ISSUE THREAD

**Issue by wburnett** [gerhalt/mining-camp#11]
Hi!

One of my coworkers linked me this repo, and I noticed it was last tested on an older version of Terraform that was running before HCL2 released. Would you be open to moving to the current version if I can get the PR done and tested?

**Comment by gerhalt** [comment]
Ah, missed this alert. Sure, I'd be happy to. Apologies for the delayed response.

**Comment by gerhalt** [comment]
Switched and tested with Terraform 12.24, including making the required config changes.
