### ISSUE TITLE
Upgradability

### ISSUE THREAD

**Issue by SeanHansell** [gerhalt/mining-camp#12]
Mostly minor, but the git repo doesn't have a .gitignore file, so files we modify or get modified are being tracked by git. This makes it difficult to git pull or upgrade this repo as and when you make changes. 

I believe the following files should be ignored and replaced by .example files, steps added to the README (or an initialization script) for copying the example files to the real files. This will allow you to upgrade the examples as you will without mucking with users' existing configs.

	ansible/files/prospector.cfg
	ansible/group_vars/all
	terraform/variables.tf

These files shouldn't be tracked at all

	terraform/.terraform/
	terraform/terraform.tfstate
	terraform/terraform.tfstate.backup

There are probably more but this is as far as I got before thinking I should open this issue.

**Comment by gerhalt** [comment]
Good idea. I've started some upgrade work; I should have time to get this fixed this weekend.

I was also debating the usefulness of a wizard that could prompt and populate config file templates, rather than having `.example` files?

**Comment by SeanHansell** [comment]
Because one change takes 5 minutes and the other requires dev time 😉
