### ISSUE TITLE
Not an Issue - Just props!

### ISSUE THREAD

**Issue by tmoon8730** [gerhalt/mining-camp#21]
Hey there,
This really isn't an issue so feel free to delete this if you want. Just wanted to say that I just used your system to setup my own server and it works very well! With minimal difficulties (at least as far as server setups go) everything is working!

Genius idea to use the spot instances with S3 backups!

**Comment by gerhalt** [comment]
Hey, I appreciate it! I've got a pretty exciting set of upcoming features to alleviate some of the remaining manual pieces, especially auto-provisioning. If you have pain points or suggestions on what you'd like to see fixed, let me know!
